[package]
name = "sndlink"
version = "0.1.0"
authors = ["Karolin Varner <karo@cupdev.net>"]
edition = "2018"

[dependencies]
portaudio = "0.7.0"
clap = "2.33.0"
byteorder = "1.3.1"
crossbeam = "0.7"
opus = "0.2.1"
